In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
## Sentences

sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',
     ]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
## Define the vocabulary size

voc_size=10000

In [20]:
## One Hot Representation

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1885, 1143, 6796, 2067],
 [1885, 1143, 6796, 964],
 [1885, 4007, 6796, 8366],
 [947, 272, 8778, 7727, 6766],
 [947, 272, 8778, 7727, 784],
 [8052, 1885, 1846, 6796, 4841],
 [4074, 9356, 9713, 7727]]

In [21]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [22]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1885 1143 6796 2067]
 [   0    0    0    0 1885 1143 6796  964]
 [   0    0    0    0 1885 4007 6796 8366]
 [   0    0    0  947  272 8778 7727 6766]
 [   0    0    0  947  272 8778 7727  784]
 [   0    0    0 8052 1885 1846 6796 4841]
 [   0    0    0    0 4074 9356 9713 7727]]


In [23]:
## Feature representation

dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 36ms/step


array([[[ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,
          0.0192211 ,  0.02310104,  0.00415931,  0.03544476,
         -0.0376664 , -0.00508062],
        [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,
          0.0192211 ,  0.02310104,  0.00415931,  0.03544476,
         -0.0376664 , -0.00508062],
        [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,
          0.0192211 ,  0.02310104,  0.00415931,  0.03544476,
         -0.0376664 , -0.00508062],
        [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,
          0.0192211 ,  0.02310104,  0.00415931,  0.03544476,
         -0.0376664 , -0.00508062],
        [ 0.03233515, -0.00565472, -0.04953751,  0.02675981,
         -0.00850214,  0.00012448, -0.00654257,  0.01181822,
          0.03113972,  0.02671507],
        [ 0.00407629, -0.03572626, -0.02759967,  0.01748559,
          0.0142878 , -0.00879482, -0.02263926, -0.00899897,
          0.00040127,  0.02663301],
        [-0.0472908 ,  0.00979719, -0.0281443 , -0.0

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 1885, 1143, 6796, 2067])

In [28]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 30ms/step


array([[ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,  0.0192211 ,
         0.02310104,  0.00415931,  0.03544476, -0.0376664 , -0.00508062],
       [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,  0.0192211 ,
         0.02310104,  0.00415931,  0.03544476, -0.0376664 , -0.00508062],
       [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,  0.0192211 ,
         0.02310104,  0.00415931,  0.03544476, -0.0376664 , -0.00508062],
       [ 0.0393354 , -0.01947627,  0.03071827,  0.01262874,  0.0192211 ,
         0.02310104,  0.00415931,  0.03544476, -0.0376664 , -0.00508062],
       [ 0.03233515, -0.00565472, -0.04953751,  0.02675981, -0.00850214,
         0.00012448, -0.00654257,  0.01181822,  0.03113972,  0.02671507],
       [ 0.00407629, -0.03572626, -0.02759967,  0.01748559,  0.0142878 ,
        -0.00879482, -0.02263926, -0.00899897,  0.00040127,  0.02663301],
       [-0.0472908 ,  0.00979719, -0.0281443 , -0.03217127,  0.03759478,
         0.04980955,  0.0336278 ,  0.02825869